import json, re

def parse_iam(parts):
    action = parts[2]
    params = {}
    
    iam_commands = [
        "add-client-id-to-open-id-connect-provider",
        "add-role-to-instance-profile",
        "add-user-to-group",
        "attach-group-policy",
        "attach-role-policy",
        "attach-user-policy",
        "change-password",
        "create-access-key",
        "create-account-alias",
        "create-group",
        "create-instance-profile",
        "create-login-profile",
        "create-open-id-connect-provider",
        "create-policy",
        "create-policy-version",
        "create-role",
        "create-saml-provider",
        "create-service-linked-role",
        "create-service-specific-credential",
        "create-user",
        "create-virtual-mfa-device",
        "deactivate-mfa-device",
        "delete-access-key",
        "delete-account-alias",
        "delete-account-password-policy",
        "delete-group",
        "delete-group-policy",
        "delete-instance-profile",
        "delete-login-profile",
        "delete-open-id-connect-provider",
        "delete-policy",
        "delete-policy-version",
        "delete-role",
        "delete-role-permissions-boundary",
        "delete-role-policy",
        "delete-saml-provider",
        "delete-server-certificate",
        "delete-service-linked-role",
        "delete-service-specific-credential",
        "delete-signing-certificate",
        "delete-ssh-public-key",
        "delete-user",
        "delete-user-permissions-boundary",
        "delete-user-policy",
        "delete-virtual-mfa-device",
        "detach-group-policy",
        "detach-role-policy",
        "detach-user-policy",
        "disable-organizations-root-credentials-management",
        "disable-organizations-root-sessions",
        "enable-mfa-device",
        "enable-organizations-root-credentials-management",
        "enable-organizations-root-sessions",
        "generate-credential-report",
        "generate-organizations-access-report",
        "generate-service-last-accessed-details",
        "get-access-key-last-used",
        "get-account-authorization-details",
        "get-account-password-policy",
        "get-account-summary",
        "get-context-keys-for-custom-policy",
        "get-context-keys-for-principal-policy",
        "get-credential-report",
        "get-group",
        "get-group-policy",
        "get-instance-profile",
        "get-login-profile",
        "get-mfa-device",
        "get-open-id-connect-provider",
        "get-organizations-access-report",
        "get-policy",
        "get-policy-version",
        "get-role",
        "get-role-policy",
        "get-saml-provider",
        "get-server-certificate",
        "get-service-last-accessed-details",
        "get-service-last-accessed-details-with-entities",
        "get-service-linked-role-deletion-status",
        "get-ssh-public-key",
        "get-user",
        "get-user-policy",
        "help",
        "list-access-keys",
        "list-account-aliases",
        "list-attached-group-policies",
        "list-attached-role-policies",
        "list-attached-user-policies",
        "list-entities-for-policy",
        "list-group-policies",
        "list-groups",
        "list-groups-for-user",
        "list-instance-profile-tags",
        "list-instance-profiles",
        "list-instance-profiles-for-role",
        "list-mfa-device-tags",
        "list-mfa-devices",
        "list-open-id-connect-provider-tags",
        "list-open-id-connect-providers",
        "list-organizations-features",
        "list-policies",
        "list-policies-granting-service-access",
        "list-policy-tags",
        "list-policy-versions",
        "list-role-policies",
        "list-role-tags",
        "list-roles",
        "list-saml-provider-tags",
        "list-saml-providers",
        "list-server-certificate-tags",
        "list-server-certificates",
        "list-service-specific-credentials",
        "list-signing-certificates",
        "list-ssh-public-keys",
        "list-user-policies",
        "list-user-tags",
        "list-users",
        "list-virtual-mfa-devices",
        "put-group-policy",
        "put-role-permissions-boundary",
        "put-role-policy",
        "put-user-permissions-boundary",
        "put-user-policy",
        "remove-client-id-from-open-id-connect-provider",
        "remove-role-from-instance-profile",
        "remove-user-from-group",
        "reset-service-specific-credential",
        "resync-mfa-device",
        "set-default-policy-version",
        "set-security-token-service-preferences",
        "simulate-custom-policy",
        "simulate-principal-policy",
        "tag-instance-profile",
        "tag-mfa-device",
        "tag-open-id-connect-provider",
        "tag-policy",
        "tag-role",
        "tag-saml-provider",
        "tag-server-certificate",
        "tag-user",
        "untag-instance-profile",
        "untag-mfa-device",
        "untag-open-id-connect-provider",
        "untag-policy",
        "untag-role",
        "untag-saml-provider",
        "untag-server-certificate",
        "untag-user",
        "update-access-key",
        "update-account-password-policy",
        "update-assume-role-policy",
        "update-group",
        "update-login-profile",
        "update-open-id-connect-provider-thumbprint",
        "update-role",
        "update-role-description",
        "update-saml-provider",
        "update-server-certificate",
        "update-service-specific-credential",
        "update-signing-certificate",
        "update-ssh-public-key",
        "update-user",
        "upload-server-certificate",
        "upload-signing-certificate",
        "upload-ssh-public-key",
        "wait",
        "wizard"
    ]
    
    create_actions = [cmd for cmd in iam_commands if re.match(r'^create', cmd)]
    
    if re.match(r'^create', action):
        pass
    elif iam_commands in action:
        return []
    else:
        update = action
    
    # --key value 형태 파싱
    for i in range(3, len(parts)):
        if parts[i].startswith('--'):
            key = parts[i].lstrip('-')
            if i + 1 < len(parts):
                value = parts[i+1]
                #JSON 형태인지 확인 후 디코딩
                if value.strip().startswith('{'):
                    try:
                        value = json.loads(value)
                    except json.JSONDecodeError:
                        pass
                params[key] = value
    print(params)
    #IAM 동작 분류
    identifier = params.get('user-name') or params.get('role-name') or params.get('group-name')
    
    return action, identifier, params